[book]
title = "Defect Studio"
authors = ["Team"]
description = "Defect Studio Project Documentation"
language = "en"
src = "mdbook"

[output.html]
default-theme = "light"
preferred-dark-theme = "dark"
additional-css = ["mdbook/custom.css"]
