"""Write the bevel diagnostic gallery as a Defect Studio project.

Every endpoint decoration kind (rows) crossed with a set of bevel settings (columns), each one a
short bevelled Flat ribbon in the project's structure-free "Project Scene"
(scene_objects.yaml -> projectObjects, task 49). Open it with

    DefectStudio --project=tests/fixtures/bevel-gallery

The scene is generated, not hand-authored, so it can be regenerated byte-for-byte after a change to
the grid. Edit ROWS / COLUMNS below, re-run, commit the output.

    python scripts/python/make_bevel_gallery.py [output_dir]
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

# Every PathDecorationKind plus the legacy OpenArrow name the YAML reader accepts
# (src/IO/SceneObjectsYaml.cpp, validDecoration). None is the undecorated control row.
ROWS = ["None", "Arrow", "Stealth", "Latex", "OpenArrow", "Bar", "Circle", "Square", "Diamond", "Kite"]

# (label, ribbon_bevel, ribbon_bevel_segments, ribbon_bevel_shape, curved)
# Column 0 is the sharp reference every bevelled column is compared against.
COLUMNS = [
    ("sharp", 0.0, 1, 0.5, False),
    ("chamfer 0.02", 0.02, 1, 0.5, False),
    ("0.04 x3", 0.04, 3, 0.5, False),
    ("0.06 x8 round", 0.06, 8, 0.5, False),
    ("0.04 x4 shape 1.0", 0.04, 4, 1.0, False),
    ("0.04 x3 arc", 0.04, 3, 0.5, True),
]

LENGTH = 2.0          # each path runs from x to x + LENGTH
COLUMN_PITCH = 3.2    # centre-to-centre spacing along x
ROW_PITCH = 1.6       # spacing along -y, top row first
WIDTH = 0.3           # ribbon width
THICKNESS = 0.15      # Flat ribbon thickness - a bevel needs a solid to cut
DECORATION_SCALE = 1.0


def fmt(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


def vec(values) -> str:
    return "[" + ", ".join(fmt(v) for v in values) + "]"


def path_entry(row: int, column: int, decoration: str, spec) -> str:
    label, bevel, segments, shape, curved = spec
    x0 = column * COLUMN_PITCH
    y = -row * ROW_PITCH
    start = (x0, y, 0.0)
    end = (x0 + LENGTH, y, 0.0)
    if curved:
        # A 90 degree arc in the ribbon plane: exercises the decoration on a turning frame.
        segment = (
            "        - kind: Arc\n"
            "          planeNormal: [0, 0, 1]\n"
            f"          signedSweepRadians: {fmt(math.pi / 2)}\n"
        )
    else:
        segment = "        - kind: Line\n"
    name = f"{decoration} | {label}"
    key = f"bevel-gallery-r{row:02d}-c{column:02d}"
    return (
        "    - kind: ScenePath\n"
        f"      persistKey: {key}\n"
        f"      name: \"{name}\"\n"
        "      visible: true\n"
        "      renderable: true\n"
        "      nodes:\n"
        f"        - position: {vec(start)}\n"
        f"        - position: {vec(end)}\n"
        "      segments:\n"
        f"{segment}"
        "      style:\n"
        "        profile: Flat\n"
        "        ribbon_normal: [0, 0, 1]\n"
        f"        ribbon_thickness: {fmt(THICKNESS)}\n"
        f"        ribbon_bevel: {fmt(bevel)}\n"
        f"        ribbon_bevel_segments: {segments}\n"
        f"        ribbon_bevel_shape: {fmt(shape)}\n"
        f"        width: {fmt(WIDTH)}\n"
        "        join: Bevel\n"
        "        cap: Butt\n"
        "        depthMode: DepthTest\n"
        "        color: [0.85, 0.55, 0.2]\n"
        "        alpha: 1\n"
        "        startDecoration: None\n"
        f"        endDecoration: {decoration}\n"
        f"        endDecorationLengthScale: {fmt(DECORATION_SCALE)}\n"
        f"        endDecorationWidthScale: {fmt(DECORATION_SCALE)}\n"
        "        end_decoration_filled: true\n"
    )


def scene_objects() -> str:
    entries = [
        path_entry(row, column, decoration, spec)
        for row, decoration in enumerate(ROWS)
        for column, spec in enumerate(COLUMNS)
    ]
    return "formatVersion: 2\nstructures: []\nprojectObjects:\n" + "".join(entries)


MANIFEST = """uuid: 5f3c2a1e-bevel-gallery-0000-000000000001
name: bevel-gallery
created_at: 1790899200
last_modified: 1790899200
format_version: 1
roots: []
irrep_labels: []
"""


def main() -> int:
    repo = Path(__file__).resolve().parents[2]
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else repo / "tests" / "fixtures" / "bevel-gallery"
    out.mkdir(parents=True, exist_ok=True)
    (out / "manifest.yaml").write_text(MANIFEST, encoding="utf-8", newline="\n")
    (out / "scene_objects.yaml").write_text(scene_objects(), encoding="utf-8", newline="\n")
    print(f"wrote {len(ROWS) * len(COLUMNS)} paths to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
