#include "Core/dspch.hpp"

#include "Presentation/Panels/ElementCatalogPanel.hpp"

#include <cctype>
#include <cstdio>
#include <map>
#include <sstream>

#include <imgui.h>

#include "Core/Commands/CommandRegistry.hpp"
#include "Core/Logging/Logger.hpp"
#include "IO/AtomStyleIO.hpp"
#include "Presentation/Panels/PeriodicTableGrid.hpp"
#include "Renderer/Commands/RendererAtomEditCommands.hpp"

namespace DefectStudio
{
	namespace
	{
		struct ElectronSubshell
		{
			int principalQuantumNumber = 0;
			char subshell = 's';
			int electronCount = 0;
		};

		// Parses ElementProperties::electronConfiguration ("1s2 2s2 2p2") into per-subshell entries -
		// generated by pymatgen's Element.full_electronic_structure, see scripts/python/
		// generate_element_extra_properties.py.
		[[nodiscard]] std::vector<ElectronSubshell> ParseElectronConfiguration(const std::string &configuration)
		{
			std::vector<ElectronSubshell> result;
			std::istringstream stream(configuration);
			std::string token;
			while (stream >> token)
			{
				std::size_t pos = 0;
				int n = 0;
				while (pos < token.size() && std::isdigit(static_cast<unsigned char>(token[pos])))
					n = n * 10 + (token[pos++] - '0');
				if (pos >= token.size() || n <= 0)
					continue;
				const char subshell = token[pos++];
				int count = 0;
				while (pos < token.size() && std::isdigit(static_cast<unsigned char>(token[pos])))
					count = count * 10 + (token[pos++] - '0');
				result.push_back(ElectronSubshell{n, subshell, count});
			}
			return result;
		}

		[[nodiscard]] const char *ShellLetter(int principalQuantumNumber)
		{
			static const char *kLetters[] = {"K", "L", "M", "N", "O", "P", "Q"};
			if (principalQuantumNumber >= 1 && principalQuantumNumber <= 7)
				return kLetters[principalQuantumNumber - 1];
			return "?";
		}
	} // namespace

	ElementCatalogPanel::ElementCatalogPanel(
		RendererLayer &layer,
		WeakRef<CommandRegistry> commandRegistry,
		AtomStyleTable atomStyleTable,
		ElementPropertiesTable elementPropertiesTable,
		Path atomStylesPath,
		std::string title,
		bool visibleByDefault)
		: IPanel(std::move(title), visibleByDefault),
		  m_Layer(layer),
		  m_CommandRegistry(std::move(commandRegistry)),
		  m_AtomStyleTable(std::move(atomStyleTable)),
		  m_ElementPropertiesTable(std::move(elementPropertiesTable)),
		  m_AtomStylesPath(std::move(atomStylesPath))
	{
	}

	Ref<IPanel> ElementCatalogPanel::Clone() const
	{
		return CreateRef<ElementCatalogPanel>(*this);
	}

	void ElementCatalogPanel::drawSelectedElementEditor()
	{
		if (m_SelectedSymbol.empty())
		{
			ImGui::TextDisabled("Click an element above to edit its style.");
			return;
		}

		// Reseed only on an actual selection change - see m_LiveStyle's declaration for why not
		// every frame.
		if (m_LiveStyleSymbol != m_SelectedSymbol)
		{
			m_LiveStyle = m_AtomStyleTable.GetStyle(m_SelectedSymbol);
			m_LiveStyleSymbol = m_SelectedSymbol;
		}

		ImGui::Text("Element: %s", m_SelectedSymbol.c_str());

		bool changed = false;

		ImGui::SetNextItemWidth(200.0f);
		changed |= ImGui::ColorEdit3("Color", &m_LiveStyle.color.x);
		if (ImGui::IsItemActivated())
			m_DragStartStyle = m_AtomStyleTable.GetStyle(m_SelectedSymbol);
		const bool colorCommitted = ImGui::IsItemDeactivatedAfterEdit();

		ImGui::SetNextItemWidth(200.0f);
		changed |= ImGui::DragFloat("Radius", &m_LiveStyle.displayRadius, 0.01f, 0.05f, 3.0f, "%.2f");
		if (ImGui::IsItemActivated())
			m_DragStartStyle = m_AtomStyleTable.GetStyle(m_SelectedSymbol);
		const bool radiusCommitted = ImGui::IsItemDeactivatedAfterEdit();

		// Live preview: pokes the already-built render-side atom/bond color+radius directly, every
		// frame the value changes (including mid-drag) - AtomStyleTable itself stays untouched until
		// commit below, so Undo can still recover the true pre-drag value from m_DragStartStyle.
		if (changed)
			RefreshOpenWindowsForElementStyle(m_Layer, m_SelectedSymbol, m_LiveStyle);

		if (colorCommitted || radiusCommitted)
		{
			Ref<CommandRegistry> commandRegistry = m_CommandRegistry.lock();
			if (commandRegistry != nullptr)
			{
				SetElementStylePayload payload;
				payload.symbol = m_SelectedSymbol;
				payload.previousStyle = m_DragStartStyle;
				payload.newStyle = m_LiveStyle;
				CommandContext context;
				context.Set<SetElementStylePayload>("atom_edit.set_element_style_payload", std::move(payload));
				Result<CommandOutcome> result =
					commandRegistry->Execute(CommandID{"renderer.selection.set_element_style"}, std::move(context));
				if (!result)
					DS_LOG_WARN("Set element style failed: {}", result.Error().technicalDetails);
			}
		}

		if (ImGui::Button("Reset to default"))
		{
			Ref<CommandRegistry> commandRegistry = m_CommandRegistry.lock();
			if (commandRegistry != nullptr)
			{
				SetElementStylePayload payload;
				payload.symbol = m_SelectedSymbol;
				payload.previousStyle = m_AtomStyleTable.GetStyle(m_SelectedSymbol);
				payload.newStyle = AtomRenderStyle{};
				CommandContext context;
				context.Set<SetElementStylePayload>("atom_edit.set_element_style_payload", std::move(payload));
				Result<CommandOutcome> result =
					commandRegistry->Execute(CommandID{"renderer.selection.set_element_style"}, std::move(context));
				if (!result)
					DS_LOG_WARN("Reset element style failed: {}", result.Error().technicalDetails);
				else
					m_LiveStyle = AtomRenderStyle{};
			}
		}

		const ElementProperties &properties = m_ElementPropertiesTable.Get(m_SelectedSymbol);
		ImGui::Separator();
		// A single Property/Value table instead of a stack of Text lines - asked for explicitly ("the
		// whole thing was supposed to be in a table"), also gives the values a consistent aligned
		// column instead of each line's number landing wherever its label happened to end.
		if (ImGui::BeginTable(
				"##ElementProperties", 2, ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_SizingStretchProp))
		{
			ImGui::TableSetupColumn("Property", ImGuiTableColumnFlags_WidthFixed, 220.0f);
			ImGui::TableSetupColumn("Value");
			auto propertyRow = [](const char *label, const std::string &value)
			{
				ImGui::TableNextRow();
				ImGui::TableSetColumnIndex(0);
				ImGui::TextUnformatted(label);
				ImGui::TableSetColumnIndex(1);
				ImGui::TextUnformatted(value.c_str());
			};
			char buffer[64];
			std::snprintf(buffer, sizeof(buffer), "%d", properties.atomicNumber);
			propertyRow("Atomic number", buffer);
			std::snprintf(buffer, sizeof(buffer), "%.3f u", properties.mass);
			propertyRow("Atomic mass", buffer);
			std::snprintf(buffer, sizeof(buffer), "%.3f A", properties.covalentRadius);
			propertyRow("Covalent radius", buffer);
			std::snprintf(buffer, sizeof(buffer), "%.3f A", properties.vanDerWaalsRadius);
			propertyRow("Van der Waals radius", buffer);
			if (properties.electronegativity > 0.0f)
			{
				std::snprintf(buffer, sizeof(buffer), "%.2f", properties.electronegativity);
				propertyRow("Electronegativity (Pauling)", buffer);
			}
			else
			{
				propertyRow("Electronegativity (Pauling)", "n/a");
			}
			ImGui::EndTable();
		}

		const std::vector<ElectronSubshell> subshells = ParseElectronConfiguration(properties.electronConfiguration);
		if (!subshells.empty())
		{
			ImGui::Separator();
			ImGui::Text("Electron configuration (%d electrons)", properties.atomicNumber);

			// Grouped by principal shell (K/L/M/...) - the raw fill-order string alone answers "what
			// orbitals are filled", grouping also answers "how many electrons per shell", which is
			// the other half of what was asked for.
			std::map<int, std::pair<std::string, int>> byShell;
			for (const ElectronSubshell &subshell : subshells)
			{
				std::pair<std::string, int> &entry = byShell[subshell.principalQuantumNumber];
				if (!entry.first.empty())
					entry.first += ' ';
				entry.first += std::to_string(subshell.principalQuantumNumber) + subshell.subshell + std::to_string(subshell.electronCount);
				entry.second += subshell.electronCount;
			}

			// Fixed widths sized to the HEADER text at 1x font scale (not just the data) - "Electrons"
			// was clipping to "Elect..." at the old 80px, the actual complaint behind "can't tell if
			// it's the font or what".
			if (ImGui::BeginTable(
					"##ElectronShells", 3, ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_SizingStretchProp))
			{
				ImGui::TableSetupColumn("Shell", ImGuiTableColumnFlags_WidthFixed, 110.0f);
				ImGui::TableSetupColumn("Subshells");
				ImGui::TableSetupColumn("Electrons", ImGuiTableColumnFlags_WidthFixed, 110.0f);
				ImGui::TableHeadersRow();
				for (const auto &[shell, data] : byShell)
				{
					ImGui::TableNextRow();
					ImGui::TableSetColumnIndex(0);
					ImGui::Text("n=%d (%s)", shell, ShellLetter(shell));
					ImGui::TableSetColumnIndex(1);
					ImGui::TextUnformatted(data.first.c_str());
					ImGui::TableSetColumnIndex(2);
					ImGui::Text("%d", data.second);
				}
				ImGui::EndTable();
			}
		}
	}

	void ElementCatalogPanel::Render()
	{
		if (!IsVisible())
			return;

		ImGui::SetNextWindowSize(ImVec2(1260.0f, 900.0f), ImGuiCond_FirstUseEver);
		bool windowOpen = true;
		if (!ImGui::Begin(GetTitle().c_str(), &windowOpen))
		{
			ImGui::End();
			SetVisible(windowOpen);
			return;
		}

		if (ImGui::RadioButton("Style color", m_ColorMode == ElementColorMode::Style))
			m_ColorMode = ElementColorMode::Style;
		ImGui::SameLine();
		if (ImGui::RadioButton("Category", m_ColorMode == ElementColorMode::Category))
			m_ColorMode = ElementColorMode::Category;

		ImGui::SetWindowFontScale(1.2f);
		const std::string clicked = DrawPeriodicTableGrid(
			m_Layer,
			[&](const std::string &symbol) -> glm::vec3
			{
				if (m_ColorMode == ElementColorMode::Category)
					return CategoryColor(ClassifyElement(m_ElementPropertiesTable.Get(symbol).atomicNumber));
				return m_AtomStyleTable.GetStyle(symbol).color;
			},
			m_SelectedSymbol, ImVec2(54.0f, 46.0f));
		ImGui::SetWindowFontScale(1.0f);
		if (!clicked.empty())
			m_SelectedSymbol = clicked;

		ImGui::Separator();
		drawSelectedElementEditor();

		ImGui::Separator();
		if (ImGui::Button("Save to file"))
		{
			std::string error;
			if (AtomStyleIO::SaveToFile(m_AtomStylesPath, m_AtomStyleTable.AllStyles(), m_AtomStyleTable.GetVacancyStyle(), error))
				m_StatusMessage = "Saved to " + m_AtomStylesPath.String();
			else
				m_StatusMessage = "Save failed: " + error;
		}
		if (!m_StatusMessage.empty())
			ImGui::TextDisabled("%s", m_StatusMessage.c_str());

		ImGui::End();
		SetVisible(windowOpen);
	}
} // namespace DefectStudio
