#include <gtest/gtest.h>

#include "IO/SceneObjectsIO.hpp"

namespace DefectStudio::Tests
{
	namespace
	{
		PersistedScenePath BevelledArrow()
		{
			PersistedScenePath path;
			path.persistKey = "gallery-arrow";
			path.nodes = {{{0, 0, 0}}, {{2, 0, 0}}};
			path.segments.resize(1);
			path.segments[0].kind = PersistedPathSegmentKind::Line;
			path.style.profile = "Flat";
			path.style.ribbonThickness = 0.3f;
			path.style.ribbonBevel = 0.07f;
			path.style.ribbonBevelSegments = 4;
			path.style.ribbonBevelShape = 0.8f;
			path.style.endDecoration = "Stealth";
			path.style.endDecorationLengthScale = 1.5f;
			return path;
		}
	} // namespace

	// Spec criterion 1: projectObjects round-trips, decoration and bevel included, next to (and
	// separate from) the structure-scoped collection.
	TEST(SceneObjectsProjectObjectsIOTests, ProjectObjectsRoundTripNextToStructures)
	{
		SceneObjectsFile file;
		file.structures.push_back({"structures/NV/POSCAR", {}});
		file.projectObjects.push_back(BevelledArrow());

		SceneObjectsFile loaded;
		std::vector<StructuredError> warnings;
		std::string error;
		ASSERT_TRUE(SceneObjectsIO::Parse(SceneObjectsIO::Serialize(file), loaded, warnings, error)) << error;

		EXPECT_EQ(loaded.formatVersion, file.formatVersion);
		ASSERT_EQ(loaded.structures.size(), 1u);
		EXPECT_TRUE(loaded.structures[0].objects.empty());
		ASSERT_EQ(loaded.projectObjects.size(), 1u);
		const auto &path = std::get<PersistedScenePath>(loaded.projectObjects[0]);
		EXPECT_EQ(path.persistKey, "gallery-arrow");
		EXPECT_EQ(path.style.endDecoration, "Stealth");
		EXPECT_FLOAT_EQ(path.style.endDecorationLengthScale, 1.5f);
		EXPECT_FLOAT_EQ(path.style.ribbonBevel, 0.07f);
		EXPECT_EQ(path.style.ribbonBevelSegments, 4);
		EXPECT_FLOAT_EQ(path.style.ribbonBevelShape, 0.8f);
	}

	// Spec criterion 1, second half: a file written before projectObjects existed loads with an
	// empty project scene and no warning.
	TEST(SceneObjectsProjectObjectsIOTests, FileWithoutProjectObjectsLoadsAnEmptyProjectScene)
	{
		const char *legacy =
			"formatVersion: 2\n"
			"structures:\n"
			"  - structureKey: structures/NV/POSCAR\n"
			"    objects: []\n";
		SceneObjectsFile loaded;
		std::vector<StructuredError> warnings;
		std::string error;

		ASSERT_TRUE(SceneObjectsIO::Parse(legacy, loaded, warnings, error)) << error;

		EXPECT_TRUE(loaded.projectObjects.empty());
		EXPECT_TRUE(warnings.empty());
	}

	// An empty project scene is not written at all, so saving a project that never used it leaves
	// its file byte-for-byte what older builds wrote.
	TEST(SceneObjectsProjectObjectsIOTests, EmptyProjectObjectsIsNotWritten)
	{
		SceneObjectsFile file;
		file.structures.push_back({"structures/NV/POSCAR", {}});

		EXPECT_EQ(SceneObjectsIO::Serialize(file).find("projectObjects"), std::string::npos);
	}

	// Malformed content is a load diagnostic, never a silently half-read scene - same rule the
	// parser already applies to `structures`.
	TEST(SceneObjectsProjectObjectsIOTests, ProjectObjectsThatIsNotASequenceFailsTheLoad)
	{
		const char *malformed =
			"formatVersion: 2\n"
			"structures: []\n"
			"projectObjects: 7\n";
		SceneObjectsFile loaded;
		std::vector<StructuredError> warnings;
		std::string error;

		EXPECT_FALSE(SceneObjectsIO::Parse(malformed, loaded, warnings, error));
		EXPECT_NE(error.find("projectObjects"), std::string::npos) << error;
	}
} // namespace DefectStudio::Tests

#include "Core/Utils/Path.hpp"
#include "IO/TextFileIO.hpp"

namespace DefectStudio::Tests
{
	// The committed bevel gallery (tests/fixtures/bevel-gallery, generated by
	// scripts/python/make_bevel_gallery.py) must stay loadable: every entry parsed, none
	// skipped. A generator change that writes a key the reader rejects fails here, not in the app.
	TEST(SceneObjectsProjectObjectsIOTests, BevelGalleryFixtureLoadsEveryPath)
	{
		Path cursor = Path::FromResolved(FileSystem::CurrentPath());
		for (int depth = 0; depth < 10 && !FileSystem::Exists((cursor / "pyproject.toml").Native()); ++depth)
			cursor = cursor.parent_path();
		const Path file = cursor / "tests" / "fixtures" / "bevel-gallery" / "scene_objects.yaml";

		std::string text;
		std::string readError;
		ASSERT_TRUE(TextFileIO::Load(file, text, readError)) << readError;
		SceneObjectsFile loaded;
		std::vector<StructuredError> warnings;
		std::string error;
		ASSERT_TRUE(SceneObjectsIO::Parse(text, loaded, warnings, error)) << error;

		EXPECT_TRUE(warnings.empty()) << (warnings.empty() ? std::string{} : warnings.front().technicalDetails);
		EXPECT_EQ(loaded.projectObjects.size(), 60u);
		for (const PersistedSceneObject &object : loaded.projectObjects)
			EXPECT_TRUE(std::holds_alternative<PersistedScenePath>(object));
	}
} // namespace DefectStudio::Tests
