projects:
  - path: C:\Users\fzabi\Desktop\STUDIA\Defect-Studio-mgr\mgr
    last_opened_at: 1790375237
  - path: C:\Users\fzabi\Desktop\STUDIA\Defect-Studio-mgr\test-directory\mgr
    last_opened_at: 1790375231